[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"
    asDefault = true

  [entryPoints.metrics]
    address = ":8181"


[log]
  level = "INFO"
  format = "json"
  filePath = "/var/log/traefik.log"

[accessLog]
  filePath = "/var/log/access.log"
  format = "json"
  [accessLog.fields]
    defaultMode = "keep"
    [accessLog.fields.names]
      StartUTC = "drop"

[api]
  dashboard = true
  insecure = true

[providers]
  [providers.docker]
    exposedByDefault = false
  
  # [providers.file]
  #   directory = "/providers/"
  #   watch = true

[tracing]
  addInternals = true

  [tracing.otlp]
    [tracing.otlp.http]
      endpoint = "http://tempo:3200/"

[metrics]
  addInternals = true
  [metrics.prometheus]
    entryPoint = "metrics"
